name: PyInstaller

on: [push]

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    
    - name: Checkout
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
     
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build using PyInstaller
      run: |
        pyinstaller sshchat.py --onefile
        
    - name: Upload build
      uses: actions/upload-artifact@v2.2.4
      with:
          name: sshchat.exe
          path: dist/sshchat.exe
